### ISSUE TITLE
Button does not receive interaction

### ISSUE THREAD

**Issue by hogragon** [Ezelia/EZGUI#19]
Hi, I got a problem with the button. If I make a layout component and set the position is 'bottom', the buttons inside that layout component can not receive any interactions from mouse. Is there any way to fix this?

This happen with pixi 3.0.7

**Comment by alaa-eddine** [comment]
Hi @seahorsevn  
The behaviour you are describing here can occure if you have some transparent component on top of the region where your button shows. it's not related to the positionning itself.
Can you please share your layout definition so I can check ?

**Comment by Othreumaru** [comment]
I found an issue that occurs when the container that holds EZGUI components is scaled:

``` javascript
const stage = new PIXI.Container()

    stage.scale.x = scale
    stage.scale.y = scale
```

Then the button does not get input.

This can be reproduced on https://github.com/Ezelia/EZGUI/blob/master/examples/07-input/1-simple.html probably problem relates to the fact that window region is not scaled and it filters mouse input

**Comment by alaa-eddine** [comment]
The current version of EZGUI don't support Pixi scale, because it cause inconsistencies of events detections (while checking if the mouse is inside a partially masked control) 
I don't have a good idea to support runtime scale, the best method is to scale the control settings before creating it, or destroy it / recreate it to change the size.
