### ISSUE TITLE
UglifyJs can break function names of default components

### ISSUE THREAD

**Issue by llevkin** [Ezelia/EZGUI#3]
After gulp-uglify name of components was replace to i, j .. e.t.c ( name property of component constructor ). Default components was been missed and I can't create a Button for example... Possible need to pass a second argument with classname into EZGUI.registerComponents function...

**Comment by alaa-eddine** [comment]
actually EZGUI.registerComponents already accept the component name as second parameter, if not provided he'll try to guess it (and here comes the issue with uglified code).

this will be fixed in the next build.
I'm also considering to include a build system (grunt or gulp) to make contributions easier for people who don't like Visual Studio.

**Comment by alaa-eddine** [comment]
should be fixed now :)
