### ISSUE TITLE
Background repeat?

### ISSUE THREAD

**Issue by Shadowstep33** [Ezelia/EZGUI#44]
Is there an easy way to use an image at native size (or more specifically, native resolution) and not have it tile itself? I have a window background, and I would like the window take up the whole screen but the background image to essentially be no-repeat, centered

**Comment by hiker-who-codes** [comment]
See my [pull request](https://github.com/Ezelia/EZGUI/pull/41).
It does exactly that.

See the [updated ezgui.js](https://github.com/Ezelia/EZGUI/pull/41/files) to make the changes. It's just a couple lines of code. :)

It basically adds a third option to the 'bgTiling' property in your template.json. You can now give it `x` to tile in horizontal direction, `y` to tile in vertical direction and `xy` to disable tiling. What I found is that rather than enabling the tiling in a direction, it disables tiling in the opposite direction. So this basically disables tiling in both directions. Play around with the `padding` property to achieve the desired size. `position` also takes `center` as a value.

Hope this helps, feel free to ask me anything!

**Comment by alaa-eddine** [comment]
I need to look at this, I thought that it was already implemented but I maybe forgot it.

I can't merge the pull request because ezgui.js is generated on compilation, the patch need to be applied to https://github.com/Ezelia/EZGUI/blob/master/src/GUISprite.ts file :) 

if you are not familiar with TypeScript, I'll modify it in the next update.

I also need to add a gulp script to facilitate contributions and compilations of the project

**Comment by hiker-who-codes** [comment]
I will update the pull request shortly!
Nice to see it being implemented :+1:

**Comment by Shadowstep33** [comment]
Coolio, I'll check out the pull request soon definitely can use it

**Comment by Shadowstep33** [comment]
Works great thanks! 

Seems like it doesn't keep aspect ratio of the image, but it does force the image to fit which could be a pro or con depending on how you look at it :)

Also just to clarify for anyone finding this, implementation would go something like:

```
    "ShopWindow": {
        "bg": {
            "default": "../img.png"
        },
        "bgTiling": "xy"        
    }
```

**Comment by alaa-eddine** [comment]
I merged @RandomDesigner  patch.
I think it'll need some tweak to handle aspect ratio correctly
