### ISSUE TITLE
The hover state of Button don't back to 'default' on mouseout event

### ISSUE THREAD

**Issue by llevkin** [Ezelia/EZGUI#5]

**Comment by alaa-eddine** [comment]
This one is a known bug I thought I fixed.
it's mainly due to the fact that Pixi v2, Phaser and Pixi v3 have all different event management systems, and the when fixing the hover issue in one it breaks other more important features in other.

do you have a live example of this ? I'll try to make a fix/workaround.

**Comment by llevkin** [comment]
I use Phaser.. I think this is a logic problem in "if" case in 'mouseout' event.. Workaround for phaser, but here negation in logic.. Then i remove negation everything fell into place)

**Comment by alaa-eddine** [comment]
the issue here is that Phaser and Pixi mouseout is not totally equivalent to EZGUI mouseout.

let's take a EZGUI List component (the one in the middle of this screen) : http://ezgui.ezelia.com/examples/Pixi/ 

most of the list children are masked, if you move the mouse outside of List border, mouseover will not trigger in EZGUI, but it is actually triggered in Phaser and Pixi because they only take in consideration the position of element, masks are totally ignored.

and what make things worst is that event priorities and events propagation are handled differently between Pixi and Phaser.

so it's not just a question of logic, it's really related to the way each library handle the events and the fact that I want EZGUI to be compatible with all those.

I'll maybe need to implemente a specific events handler in future version to resolve such issues.but for such changes I prefer waiting the new major Phaser version (which will no more use Pixi) to see what modifications will be needed to keep compatibility.

you can still override the default mouseover behaviour or clear it and setup your own :)

**Comment by llevkin** [comment]
Understood,  thanks)
