### ISSUE TITLE
Can't destroy UI, method is empty..

### ISSUE THREAD

**Issue by llevkin** [Ezelia/EZGUI#7]

**Comment by alaa-eddine** [comment]
I actually added the destroy method to keep compatibility with phaser, because he was complaining about it.
I don't know how Phaser use it internally.
I'll add a call to the parent destroy method, maybe it'll do the trick.

I actually never had to destroy the game GUI elements because building them take some CPU time, so I build them and use visible = true/false to show/hide them, but I understand that this can be needed.

**Comment by llevkin** [comment]
I try to create a 'hint' with changed text, width and height, but then I change width or height it re scale item and this look ugly... Then I try to destroy item and recreate...

**Comment by alaa-eddine** [comment]
here is fix, let me know if it works :)
